name: bemeli_filter
description: bemeli filters
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_math: ^2.1.0
  intl: ^0.17.0
  flutter_lints: ^2.0.1
